import os
import re

# CONFIGURATION
ASSETS_DIR = "wwwRoot"                      # Folder containing your raw assets
OUTPUT_FILE = "include/www_server/assets.h"  # Target path for the generated C++ header file

def minify_text(content, ext):
    """Safely removes comments and extra whitespace without breaking JS/CSS structure."""
    if ext == '.html':
        # Remove HTML comments <!-- ... -->
        content = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL)
    elif ext in ['.css', '.js']:
        # Remove multi-line comments /* ... */
        content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
        
        # Safely remove single-line comments // ... 
        # (Be careful not to match URLs like http://, so we look for whitespace or start of line before //)
        content = re.sub(r'(^|\s)//.*?$', r'\1', content, flags=re.MULTILINE)

    # Clean lines: strip trailing/leading spaces, but PRESERVE the line breaks (\n)
    # This prevents breaking JS code that relies on implicit semicolons or line structure.
    lines = content.splitlines()
    cleaned_lines = [line.strip() for line in lines if line.strip()]
    
    # Join back with actual newlines instead of spaces, keeping the code readable and syntactically valid
    return "\n".join(cleaned_lines)

def generate_assets():
    if not os.path.exists(ASSETS_DIR):
        print(f"Error: The target directory '{ASSETS_DIR}' does not exist!")
        return

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as out:
        # Mandatory auto-generation header warning (in English)
        out.write("// ==========================================================\n")
        out.write("// THIS FILE IS AUTO-GENERATED BY A PYTHON SCRIPT.\n")
        out.write("// DO NOT EDIT THIS FILE MANUALLY - ALL CHANGES WILL BE LOST!\n")
        out.write("// ==========================================================\n\n")
        out.write("#pragma once\n")
        out.write("#include <cstddef>\n\n")
        out.write("namespace PicoLightShow::Assets {\n\n")

        for root, _, files in os.walk(ASSETS_DIR):
            for file in sorted(files):
                file_path = os.path.join(root, file)
                
                # Create a valid C++ variable name from the filename (e.g., app.min.js -> app_min_js)
                var_name = re.sub(r'[^a-zA-Z0-9_]', '_', file).lower()
                ext = os.path.splitext(file)[1].lower()
                
                # Check if the file is already minified (contains .min.js or .min.css, etc.)
                is_already_minified = '.min.' in file.lower()
                
                # Load and optionally minify content based on extension and minification status
                if not is_already_minified and ext in ['.html', '.css', '.js', '.json', '.svg']:
                    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                        raw_content = f.read()
                    processed_content = minify_text(raw_content, ext)
                    file_bytes = processed_content.encode('utf-8')
                    asset_type = "Minified Text Asset"
                else:
                    # Binary assets OR already minified files (.min.js, .min.css) remain untouched
                    with open(file_path, 'rb') as f:
                        file_bytes = f.read()
                    asset_type = "Pre-minified / Binary Asset" if is_already_minified else "Binary Asset"

                # Detailed English comments for each generated asset
                out.write(f"    // --------------------------------------------------------\n")
                out.write(f"    // File source: '{file}'\n")
                out.write(f"    // Type: {asset_type} | Size: {len(file_bytes)} bytes\n")
                out.write(f"    // --------------------------------------------------------\n")
                
                out.write(f"    const unsigned char {var_name}[] = {{\n")

                # Write hex values in chunks of 12 for clean readability
                hex_vals = [f"0x{b:02x}" for b in file_bytes]
                for i in range(0, len(hex_vals), 12):
                    chunk = ", ".join(hex_vals[i:i+12])
                    out.write(f"        {chunk},\n")
                
                out.write("    };\n")
                out.write(f"    const size_t {var_name}_size = sizeof({var_name});\n\n")

        out.write("}\n")
    
    print(f"Successfully generated assets header at: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_assets()