#ifndef PICO_LIGHT_SHOW_CONSTANTS_H_
#define PICO_LIGHT_SHOW_CONSTANTS_H_

#define WS2812_PIN 14
#define IS_RGBW false
#define TARGET_FPS 30
#define FRAME_TIME_MS (1000 / TARGET_FPS)
#define WS_STATE_MACHINE_INDEX 0
#define WS_PIO_INSTANCE pio0_hw

#define DEFAULT_WIFI_SSID "PicoLightShow"
#define DEFAULT_WIFI_PASSWORD "123456789"

#define DDP_PORT 4048
#define DDP_TIMEOUT_MS 3000

#endif // PICO_LIGHT_SHOW_CONSTANTS_H_
