#ifndef PICO_LIGHT_SHOW_CONSTANTS_H_
#define PICO_LIGHT_SHOW_CONSTANTS_H_

#define WS2812_PIN 2
#define IS_RGBW false
#define MINIMAL_REDRAW_DELAY 1
#define WS_STATE_MACHINE_INDEX 0
#define WS_PIO_INSTANCE pio0_hw

#define DEFAULT_WIFI_SSID "PicoLightShow"
#define DEFAULT_WIFI_PASSWORD "123456789"

#endif // PICO_LIGHT_SHOW_CONSTANTS_H_
